CREATE TABLE IF NOT EXISTS users_model (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_name varchar not null,
    user_email varchar not null unique
);

CREATE TABLE IF NOT EXISTS items_model (
    item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_name varchar not null,
    item_description varchar not null,
    item_availability boolean not null,
    item_owner_id BIGINT not null REFERENCES users_model(user_id),
    item_request_id BIGINT
);

CREATE TABLE IF NOT EXISTS bookings_model (
    booking_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_start timestamp without time zone not null,
    booking_end timestamp without time zone not null,
    booking_item_id BIGINT not null REFERENCES items_model(item_id),
    booking_booker_id BIGINT not null REFERENCES users_model(user_id),
    booking_status varchar not null
);

CREATE TABLE IF NOT EXISTS comments_model (
    comment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    comment_text varchar not null,
    comment_author_id BIGINT not null REFERENCES users_model(user_id),
    comment_item_id BIGINT not null REFERENCES items_model(item_id),
    comment_created timestamp not null
);