DROP TABLE IF EXISTS bookings_model, items_model, item_requests_model, comments_model, users_model;

CREATE TABLE IF NOT EXISTS users_model (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY not null PRIMARY KEY,
    user_name varchar(255) not null,
    user_email varchar(255) not null unique
);

CREATE TABLE IF NOT EXISTS items_model (
    item_id BIGINT GENERATED BY DEFAULT AS IDENTITY not null PRIMARY KEY,
    item_name varchar(255) not null,
    item_description varchar(5000) not null,
    item_availability boolean not null,
    item_owner_id BIGINT not null REFERENCES users_model(user_id),
    item_request_id BIGINT
);

CREATE TABLE IF NOT EXISTS bookings_model (
    booking_id BIGINT GENERATED BY DEFAULT AS IDENTITY not null PRIMARY KEY,
    booking_start timestamp without time zone not null,
    booking_end timestamp without time zone not null,
    booking_item BIGINT not null REFERENCES items_model(item_id),
    booking_booker BIGINT not null REFERENCES users_model(user_id),
    booking_status varchar(50) not null
);

CREATE TABLE IF NOT EXISTS comments_model (
    comment_id BIGINT GENERATED BY DEFAULT AS IDENTITY not null PRIMARY KEY,
    comment_text varchar(5000) not null,
    comment_user_id BIGINT not null REFERENCES users_model(user_id),
    comment_item_id BIGINT not null REFERENCES items_model(item_id),
    comment_created timestamp not null
);

CREATE TABLE IF NOT EXISTS item_requests_model (
    request_id BIGINT GENERATED BY DEFAULT AS IDENTITY not null PRIMARY KEY,
    request_description varchar(5000) not null,
    request_requester_id BIGINT not null REFERENCES users_model(user_id),
    request_created timestamp not null
);